### ISSUE TITLE
React Group Project

### ISSUE THREAD

**Issue by Alhajideen** [Alhajideen/Space--Travelers#24]
Hi,
Here, Me and @KanzaTahreem have set up the Kanban board and assigned actions accordingly.
There are just two of us in the group.
[Here is the Link to the project](https://github.com/Alhajideen/Space--Travelers/projects/1).

Kind regards.

**Comment by danmainah** [comment]
Hi @Alhajideen and @KanzaTahreem , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Good design
✔️  Good PR and Description


# Required Changes ♻️

- [ ] Kindly ensure you have added all the required cards for this project, you are missing one card for[ displaying reserved rockets in your profile ](https://github.com/microverseinc/curriculum-react-redux/issues/68)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @danmainah and @KanzaTahreem 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
